//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RollCall.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attendance
    {
        public string ID { get; set; }
        public string NAME { get; set; }
        public string BU { get; set; }
        public string LINENAME { get; set; }
        public string CLASS { get; set; }
        public string state1 { get; set; }
        public string reason1 { get; set; }
        public string note1 { get; set; }
        public string state2 { get; set; }
        public string reason2 { get; set; }
        public string note2 { get; set; }
        public System.DateTime date1 { get; set; }
        public Nullable<System.DateTime> date2 { get; set; }
        public Nullable<double> time1 { get; set; }
        public int keyid { get; set; }
    }
}
