//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RollCall.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DataModelContainer : DbContext
    {
        public DataModelContainer()
            : base("name=DataModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Staff> Staff { get; set; }
        public virtual DbSet<LienNumber> LienNumber { get; set; }
        public virtual DbSet<Attendance> Attendance { get; set; }
        public virtual DbSet<WorkOvertime> WorkOvertime { get; set; }
        public virtual DbSet<PhoneUsers> PhoneUsers { get; set; }
        public virtual DbSet<SpecialCase> SpecialCase { get; set; }
        public virtual DbSet<StaffXXX> StaffXXX { get; set; }
        public virtual DbSet<Sys_Users> Sys_Users { get; set; }
    }
}
