//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RollCall.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DepartmentCompilation
    {
        public int id { get; set; }
        public string department { get; set; }
        public string deptName { get; set; }
        public int nums { get; set; }
        public string createEmp { get; set; }
        public System.DateTime createTime { get; set; }
        public string modifyEmp { get; set; }
        public Nullable<System.DateTime> modifyTime { get; set; }
        public string item1 { get; set; }
        public string item2 { get; set; }
        public string item3 { get; set; }
    }
}
