//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RollCall.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LienNumber
    {
        public string type1 { get; set; }
        public string linename { get; set; }
        public Nullable<int> OrderbBy { get; set; }
        public int id { get; set; }
    }
}
