//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RollCall.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_Users
    {
        public string Emp_no { get; set; }
        public string Password { get; set; }
        public string Department { get; set; }
        public Nullable<System.DateTime> Curr_time { get; set; }
        public Nullable<int> State { get; set; }
        public string Name { get; set; }
        public string Item1 { get; set; }
        public string Item2 { get; set; }
        public string Item3 { get; set; }
    }
}
